version: '3.8'

services:
  service1:
    build: ./src/services/service1
    environment:
      PYTHONPATH: /app/src
    command: uvicorn services.service1.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  service2:
    build: ./src/services/service2
    environment:
      PYTHONPATH: /app/src
    command: uvicorn services.service2.app:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"

  service3:
    build: ./src/services/service3
    environment:
      PYTHONPATH: /app/src
    command: uvicorn services.service3.app:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"